homeassistant:
  customize:
    sensor.sensor_bathroom_ac_temperature:
      friendly_name: Temperatura
      icon: mdi:thermometer
    sensor.sensor_bathroom_ac_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
      device_class: humidity
#    sensor.sensor_bathroom_ac_pressure:
#      friendly_name: Presi처n
#      icon: mdi:weather-cloudy
    sensor.sensor_bathroom_ac_illumination:
      friendly_name: Iluminaci처n
      icon: mdi:lightbulb-on

    sensor.sensor_bathroom_ac_snum:
      friendly_name: 'Sample # (aseo)'

#    binary_sensor.sensor_bathroom_ac_mov1:
#      friendly_name: 'Movimiento (aseo)'
    binary_sensor.sensor_bathroom_ac_online:
      friendly_name: Aseo Online
    switch.ac_dry_contact:
      friendly_name: "Aire acondicionado"
      icon: mdi:air-conditioner

binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_esp_bathroom_ac_lwt
    name: sensor_bathroom_ac_online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

#  - platform: mqtt
#    device_class: motion
#    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
#    value_template: "{{ value_json.sample.bin[0]}}"
#    name: sensor_bathroom_ac_mov1
#    qos: !secret mqtt_default_qos
#    payload_on: 1
#    payload_off: 0
#    availability_topic: !secret mqtt_topic_esp_bathroom_ac_lwt
#    payload_available: "online"
#    payload_not_available: "offline"

sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: "{% if 'temp' in value_json.sample %}{{ value_json.sample.temp | round(1) }}{% else %}unknown{% endif %}"
    name: sensor_bathroom_ac_temperature
    unit_of_measurement: "째C"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: "{% if 'hum' in value_json.sample %}{{ value_json.sample.hum | round(1) }}{% else %}unknown{% endif %}"
    name: sensor_bathroom_ac_humidity
    unit_of_measurement: "%"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: "{% if 'lux' in value_json.sample %}{{ value_json.sample.lux}}{% else %}unknown{% endif %}"
    name: sensor_bathroom_ac_illumination
    unit_of_measurement: "lx"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: "{{ value_json.sample.snum | int }}"
    unit_of_measurement: "sample"
#    json_attributes: 'ip,bssid,rssi,wifi_ap,clientid,status,network,ts,sample'
    json_attributes_topic: !secret mqtt_topic_esp_bathroom_ac_status
    name: sensor_bathroom_ac_snum
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: history_stats
    name: Horas de AC
    entity_id: switch.ac_dry_contact
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

switch:
  - platform: mqtt
    name: ac_dry_contact
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: '{"relay1": {{ value_json.sample.relays[0]}}}'
    command_topic: !secret mqtt_topic_esp_bathroom_ac_command
    payload_on: '{"relay1": 1}'
    payload_off: '{"relay1": 0}'
    availability_topic: !secret mqtt_topic_esp_bathroom_ac_lwt
    payload_available: "online"
    payload_not_available: "offline"
    optimistic: false
    qos: 2
    retain: true


climate:
  - platform: generic_thermostat
    name: Termostato AC
    heater: switch.ac_dry_contact
    ac_mode: True
    target_sensor: sensor.temperatura_ac
    min_temp: 20
    max_temp: 30
#    target_temp: 27
    cold_tolerance: 1.0
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 10
    keep_alive:
      minutes: 5
#    initial_hvac_mode: "off"
#    away_temp: 30

  # TODO integrate both climate comps in one cold/heat one
  - platform: generic_thermostat
    name: Calefacci처n
    heater: switch.ac_dry_contact
    ac_mode: False
    target_sensor: sensor.temperatura_ac
    min_temp: 16
    max_temp: 27
    target_temp: 18
    cold_tolerance: 1.0
    hot_tolerance: 1.0
    min_cycle_duration:
      minutes: 10
    keep_alive:
      minutes: 5
#    initial_hvac_mode: "off"
    away_temp: 16
