###############################################################################
# enerPI current meter
###############################################################################
homeassistant:
  customize:
    sensor.nas_home_status:
      friendly_name: QNAP Status
    sensor.nas_home_cpu_usage:
      friendly_name: QNAP CPU Usage
    sensor.nas_home_memory_usage:
      friendly_name: QNAP Memory Usage
    sensor.nas_home_system_temperature:
      friendly_name: QNAP Temperature
    sensor.nas_home_network_down_eth0:
      friendly_name: QNAP Download
    sensor.nas_home_network_up_eth0:
      friendly_name: QNAP Upload
    sensor.nas_home_volume_used_datavol1:
      friendly_name: Disk used

sensor:
  - platform: qnap
    host: !secret nas_qnap_host
    username: !secret nas_qnap_username
    password: !secret nas_qnap_password
    nics: eth0
    scan_interval: 60
    timeout: 10
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - system_temp
#      - drive_temp
#      - drive_smart_status
      - network_tx
      - network_rx
      - volume_percentage_used

  - platform: nut
    host: !secret nas_qnap_host
    username: !secret nas_qnap_username
    password: !secret nas_qnap_password
    alias: qnapups
    resources:
      - ups.status.display
      - input.voltage
      - output.voltage
      - ups.load
      - battery.charge
      - battery.runtime
      #- ups.realpower.nominal == 900 W

  - platform: template
    sensors:
      nut_ups_power:
        value_template: "{{ (states.sensor.nut_ups_load.state | int) * 9 }}"
        unit_of_measurement: W
