###############################################################################
# SONOFF DEVICES
###############################################################################

homeassistant:
  customize:
#    switch.bomba_circ_acs:
#      icon: mdi:radiator
#      friendly_name: Bomba circulación ACS
#      homebridge_switch_type: outlet
    switch.calentador:
      icon: mdi:radiator
      friendly_name: Calentador eléctrico
    switch.sonoff_simple_1:
      icon: mdi:power-plug
      friendly_name: Sonoff
#    switch.circuito_termo:
#      icon: mdi:radiator
#      friendly_name: Circuito de Termo
#      homebridge_name: Circuito de Termo
#      homebridge_switch_type: outlet
#    cover.sonoff_cover_ventanal:
#      friendly_name: Ventanal
#      homebridge_name: Ventanal
#      homebridge_cover_type: rollershutter
#    cover.sonoff_cover_puerta_terraza:
#      homebridge_name: Puerta terraza
#      friendly_name: Puerta terraza
#      homebridge_cover_type: rollershutter
    sensor.sonoff_pow_1:
      icon: mdi:radiator
      friendly_name: Consumo en termo

    input_boolean.use_heater:
      icon: mdi:toggle-switch

input_boolean:
  use_heater:
    name: Encendido diario de calentador
#    initial: on

switch:
# Sonoff POW 16A
  - platform: mqtt
#    name: circuito_termo
    name: calentador
    state_topic: "sonoff/pow/1/stat"
    command_topic: "sonoff/pow/1"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: true

## Sonoff dual
#  - platform: mqtt
#    name: calentador
#    state_topic: "sonoff/dual1/stat1"
#    command_topic: "sonoff/dual1"
#    qos: 1
#    payload_on: "1on"
#    payload_off: "1off"
#    retain: true
#
#  - platform: mqtt
#    name: bomba_circ_acs
#    state_topic: "sonoff/dual1/stat2"
#    command_topic: "sonoff/dual1"
#    qos: 1
#    payload_on: "2on"
#    payload_off: "2off"
#    retain: true

# Sonoff Simple outlet
  - platform: mqtt
    name: sonoff_simple_1
#    name: bomba_circ_acs
    state_topic: "sonoff/simple1/stat"
    command_topic: "sonoff/simple1"
    qos: 1
    payload_on: "on"
    payload_off: "off"
    retain: true

# Sonoff 4ch as 2 custom covers
#cover:
#  - platform: mqttcoverswitch
#    covers:
#      sonoff_cover_ventanal:
#        friendly_name: Ventanal
#        state_switch_open_topic: "sonoff/4cover/stat4"
#        state_switch_close_topic: "sonoff/4cover/stat3"
#        command_switch_open_topic: "sonoff/4cover"
#        command_switch_close_topic: "sonoff/4cover"
#        payload_open: "4on"
#        payload_stop_open: "4off"
#        payload_close: "3on"
#        payload_stop_close: "3off"
#        delay_full_open: 27.0
#        qos: 1
#        retain: true
#        optimistic: false
#
#      sonoff_cover_puerta_terraza:
#        friendly_name: Puerta terraza
#        state_switch_open_topic: "sonoff/4cover/stat2"
#        state_switch_close_topic: "sonoff/4cover/stat1"
#        command_switch_open_topic: "sonoff/4cover"
#        command_switch_close_topic: "sonoff/4cover"
#        payload_open: "2on"
#        payload_stop_open: "2off"
#        payload_close: "1on"
#        payload_stop_close: "1off"
#        delay_full_open: 27.0
#        qos: 1
#        retain: true
#        optimistic: false

# Sonoff POW voltage and power sensors
sensor:
  - platform: mqtt
    state_topic: "sonoff/pow/1/power"
    value_template: "{{ value_json.Power }}"
    name: sonoff_pow_1
    unit_of_measurement: "W"
    json_attributes: 'Voltage'
    qos: 1
    expire_after: 60

  - platform: history_stats
    name: Horas de Termo
    entity_id: switch.calentador
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
