binary_sensor.floorplan:
  custom_ui_state_card: state-card-floorplan
  config: !include floorplan.yaml

script.start_tvshows_mode:
  hidden: true
script.start_status_sonoff_outlets:
  hidden: true
scene.golpe_de_frio:
  icon: mdi:arrow-down-bold
scene.golpe_de_calor:
  icon: mdi:arrow-up-bold
automation.apagado_de_ac:
  icon: mdi:fan-off
camera.weather_svg:
  friendly_name: Alicante
weblink.router_movistar:
  icon: mdi:router-wireless
weblink.wifi_repeater:
  icon: mdi:router-wireless
weblink.enerpi:
  icon: mdi:flash
weblink.nas_qnap:
  icon: mdi:server-network
weblink.nas_synology:
  icon: mdi:server-network
weblink.hassio_lan:
  icon: mdi:home-assistant
weblink.tv_headend:
  icon: mdi:television-guide
weblink.motioneye:
  icon: mdi:video
weblink.kodi_web_interface:
  icon: mdi:kodi
weblink.slave_hass:
  friendly_name: HA Estudio
  icon: mdi:home-assistant
weblink.slave_hass_mpd:
  friendly_name: HA Dormitorio
  icon: mdi:home-assistant
weblink.consumo_electrico:
  icon: mdi:chart-areaspline
weblink.grafana:
  icon: mdi:chart-areaspline
weblink.contabilidad:
  icon: mdi:bank
person.eugenio:
  icon: mdi:human-male
person.carmen:
  icon: mdi:human-female