#  themes: !include themes.yaml
darkorange:
  primary-color: '#ff9800'
  dark-primary-color: '#37464f'
  light-primary-color: '#62717b'
  floorplan-primary-color: "#ff9800"
  floorplan-light-primary-color: "#62717b"
  floorplan-background-color: "#37464f"
  floorplan-background-motion-color: "rgb(150, 142, 128)"
  floorplan-positive-color: "#caeb55"
  floorplan-negative-color: "#f15a24"
  floorplan-button-color: "#263137"
  floorplan-button2-color: "#263137"
  floorplan-button-border-color: "#263137"

darkred:
  # Main colors that can be changed
  dark-primary-color: "#c66900"
  disabled-text-color: "#545454"
  divider-color: "rgba(255, 255, 255, 0.12)"
  light-primary-color: "#e06c6c"
  paper-card-background-color: "#1d1d1d"
  paper-grey-200: "#191919"
  paper-item-icon-color: "#d3d3d3"
  paper-listbox-background-color: "#202020"
  primary-background-color: "#303030"
  primary-color: "#d32f2f"
  primary-text-color: "#cfcfcf"
  secondary-background-color: "#131313"
  sidebar-text_-_background: "#62717b"
  # Colors based on variables, see above
  paper-card-header-color: "var(--paper-item-icon-color)"
  paper-item-icon-active-color: "var(--primary-color)"
  paper-item-icon_-_color: "var(--primary-text-color)"
  paper-listbox-color: "var(--primary-text-color)"
  paper-grey-50: "var(--primary-text-color)"
  paper-slider-active-color: "var(--primary-color)"
  paper-slider-knob-color: "var(--primary-color)"
  paper-slider-knob-start-color: "var(--primary-color)"
  paper-slider-pin-color: "var(--primary-color)"
  paper-slider-secondary-color: "var(--light-primary-color)"
  paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
  paper-toggle-button-checked-button-color: "var(--primary-color)"
  paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
  paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
  secondary-text-color: "var(--primary-color)"
  table-row-background-color: "var(--paper-card-background-color)"
  table-row-alternative-background-color: "var(--sidebar-text_-_background)"

PmxMononight:
  # MyVariables
  base-hue: '220' #Controls the base (and accent) color hue (0-360) | 0=Red 60=Yellow 120=Green 180=Cyan 240=Blue 300=Magenta 360=Red
  base-sat: '32%' #Controls the saturation of the theme (0%-100%) | 0%=Grey 100%=Full Saturation
  # MyVar
  huesat: 'var(--base-hue), var(--base-sat),'
  # Primary Color
  primary-color: 'hsl(var(--huesat) 20%)'
  # Backgrounds
  primary-background-color: 'var(--primary-color)'
  secondary-background-color: 'hsl(var(--huesat) 16%)'
  paper-listbox-background-color: 'var(--primary-color)'
  paper-card-background-color: 'hsl(var(--huesat) 12%)'
  paper-dialog-background-color: 'var(--paper-card-background-color)'
  table-row-background-color: 'hsl(var(--huesat) 12%)'
  table-row-alternative-background-color: 'hsl(var(--huesat) 10%)'
  # Devider
  divider-color: 'hsla(0, 0%, 0%, 0)'
  dark-divider-opacity: '0'
  light-divider-opacity: '0'
  # Text colors
  primary-text-color: 'hsl(var(--huesat) 60%)'
  text-primary-color: 'hsl(var(--huesat) 60%)'
  secondary-text-color: 'hsl(var(--huesat) 60%)'
  disabled-text-color: 'hsl(var(--huesat) 70%)'
  sidebar-text_-_color: 'hsl(var(--huesat) 90%)'
  sidebar-text-color: 'hsl(var(--huesat) 90%)'
  paper-card-header-color: 'hsl(var(--base-hue), 90%, 50%)'
  # Text Adjustments
  paper-font-headline_-_letter-spacing: '-0.5px'
  paper-font-headline_-_font-weight: '500'
  paper-font-body1_-_font-weight: '500'
  # Nav Menu
  paper-listbox-color: 'hsl(var(--huesat) 50%)'
  paper-grey-50: 'hsl(var(--huesat) 50%)'
  paper-grey-200: 'hsla(var(--huesat) 26%)'
  # Paper card
  paper-item-icon-color: 'hsl(var(--huesat) 30%)'
  paper-item-icon-active-color: 'var(--paper-item-icon-color)'
  paper-item-icon_-_color: 'var(--paper-item-icon-color)'
  paper-item-selected_-_background-color: 'hsla(0, 0%, 0%, 0.2)'
  paper-tabs-selection-bar-color: 'hsla(0, 0%, 0%, 0.2)'
  # Labels
  label-badge-red: 'hsla(0, 0%, 0%, 0)'
  label-badge-border-color: 'var(--label-badge-red)'
  label-badge-background-color: 'var(--paper-card-background-color)'
  label-badge-text-color: 'var(--primary-text-color)'
  # Shadows
  shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 18%)'
  shadow-elevation-16dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 28%)'
  # Switches
  paper-toggle-button-checked-button-color: 'hsl(var(--base-hue), 90%, 50%)'
  paper-toggle-button-checked-bar-color: 'hsl(var(--huesat) 25%)'
  paper-toggle-button-unchecked-button-color: 'hsl(var(--huesat) 25%)'
  paper-toggle-button-unchecked-bar-color: 'hsl(var(--huesat) 5%)'
  # Sliders
  paper-slider-knob-color:  'hsl(var(--base-hue), 90%, 50%)'
  paper-slider-knob-start-color: 'hsl(var(--base-hue), 80%, 25%)'
  paper-slider-pin-color:  'hsl(var(--base-hue), 90%, 50%)'
  paper-slider-active-color:  'hsl(var(--base-hue), 90%, 50%)'
  paper-slider-container-color: 'hsl(var(--huesat) 28%)'
  paper-slider-secondary-color: 'hsl(var(--huesat) 90%)'
  paper-slider-disabled-active-color: 'hsl(var(--base-hue), 80%, 25%)'
  paper-slider-disabled-secondary-color: 'hsl(var(--base-hue), 80%, 25%)'
  paper-dialog-color: 'hsl(var(--base-hue), 20%, 80%)'

dark_theme:
  # Main Stuff #
  primary-color: "#1ABA92" # Primary (most of the UI)
  primary-background-color: "#303030" # Primary background colour (dialogs, e.t.c)
  secondary-background-color: "#303030" # Secondary background colour (main UI background)
  paper-card-background-color: "#424242" # Card background colour
  paper-item-icon-color: "#1ABA92" # Icon colour
  primary-text-color: "#FFFFFF" # Primary text colour
  secondary-text-color: "rgba(255, 255, 255, 0.7)" # Secondary text colour
  disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
  divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
  paper-card-header-color: "#FFFFFF" # Card header text colour

  # Nav Menu #
  paper-listbox-background-color: "#424242" # Listbox background colour
  paper-listbox-color: "#FFFFFF" # Listbox text colour
  paper-grey-200: "#616161" # Listbox selected item background colour

  # Switches #
  paper-toggle-button-checked-ink-color: "#1ABA92"
  paper-toggle-button-checked-button-color: "#1ABA92"
  paper-toggle-button-checked-bar-color: "#1ABA92"

  # Sliders #
  paper-slider-knob-color: "#1ABA92"
  paper-slider-knob-start-color: "#1ABA92"
  paper-slider-pin-color: "#1ABA92"
  paper-slider-active-color: "#1ABA92"
  paper-slider-secondary-color: "#33F2D8"

  # Tables #
  table-row-background-color: transparent
#      table-row-background-color: transparant
  table-row-alternative-background-color: transparent

minimal:
  dark-primary-color: "#192231"
  primary-color: "#98878f"
  light-primary-color: "#98878f"
  paper-toggle-button-checked-ink-color: "#494e6b"
  paper-toggle-button-checked-button-color: "#494e6b"
  paper-toggle-button-checked-bar-color: "#494e6b"
  paper-slider-knob-color: "#494e6b"
  paper-slider-knob-start-color: "#494e6b"
  paper-slider-pin-color: "#494e6b"
  paper-slider-active-color: "#494e6b"

stormy_hues:
  dark-primary-color: "#192231"
  primary-color: "#98878f"
  light-primary-color: "#98878f"
  paper-toggle-button-checked-ink-color: "#494e6b"
  paper-toggle-button-checked-button-color: "#494e6b"
  paper-toggle-button-checked-bar-color: "#494e6b"
  paper-slider-knob-color: "#494e6b"
  paper-slider-knob-start-color: "#494e6b"
  paper-slider-pin-color: "#494e6b"
  paper-slider-active-color: "#494e6b"

vintage:
  dark-primary-color: "#373f27"
  primary-color: "#636b46"
  light-primary-color: "#e9e7da"
  paper-toggle-button-checked-ink-color: "#cda34f"
  paper-toggle-button-checked-button-color: "#cda34f"
  paper-toggle-button-checked-bar-color: "#cda34f"
  paper-slider-knob-color: "#cda34f"
  paper-slider-knob-start-color: "#cda34f"
  paper-slider-pin-color: "#cda34f"
  paper-slider-active-color: "#cda34f"

done1:
  dark-primary-color: "#565656"
  primary-color: "#C09F80"
  light-primary-color: "#D7CEC7"
  paper-toggle-button-checked-ink-color: "#76323F"
  paper-toggle-button-checked-button-color: "#76323F"
  paper-toggle-button-checked-bar-color: "#76323F"
  paper-slider-knob-color: "#76323F"
  paper-slider-knob-start-color: "#76323F"
  paper-slider-pin-color: "#76323F"
  paper-slider-active-color: "#76323F"
  paper-slider-secondary-color: "#FFE0B2"
